---
- name: Initial setup
  hosts: all
  become: yes
  roles:
    - init
    - bind

- name: MySQL
  hosts: host01
  become: yes
  roles:
    - mysql

- name: Wordpress and HAproxy
  hosts: host02
  become: yes
  roles:
    - wordpress
    - haproxy

