- name: Create haproxy_exporter user
  user: 
    name: "{{ hap_exp_user }}"
    password: "{{ password }}"
    state: present
    shell: /bin/bash 
    
- name: Check that the file exists
  stat:
    path: /opt/haproxy_exporter-{{ haproxy_exp_version }}.linux-amd64.tar.gz
  register: stat_result

- name: Download haproxy exporter
  get_url:
    url: https://github.com/prometheus/haproxy_exporter/releases/download/v{{ haproxy_exp_version }}/haproxy_exporter-{{ haproxy_exp_version }}.linux-amd64.tar.gz
    dest: /opt/
  when: stat_result.stat.exists == False

- name: folder
  file:
    path: /opt/haproxy_exporter
    state: directory
    mode: '0755'

- name: untar
  unarchive:
    src: /opt/haproxy_exporter-{{ haproxy_exp_version }}.linux-amd64.tar.gz
    dest: /opt/haproxy_exporter
    remote_src: yes
    extra_opts:
      - --strip-components=1

- name: systemd haproxy_exporter
  template:
    src: haproxy_exporter.service.j2
    dest: /etc/systemd/system/haproxy_exporter.service

- name: start exporter
  service:
    name: haproxy_exporter
    state: started
    enabled: yes