---
- name: Initial setup
  hosts: servers
  become: yes
  tasks:
    - name: Create main user
      user:
        name: "{{ user }}"
        group: sudo
        password: "{{ password }}"
        shell: /bin/bash
    
    - name: Remove sudo password request
      copy:
        dest: /etc/sudoers.d/{{ user }}
        content: "{{ user }} ALL = NOPASSWD: ALL"

    - name: Push management SSH keys
      authorized_key:
        user: "{{ user }}"
        key: "{{ lookup('file', '/home/{{ user }}/.ssh/id_rsa.pub') }}"

    - name: Setup network interface
      template:
        src: files/enp0s8.yaml.j2
        dest: /etc/netplan/55-enp0s8.yaml
      notify:
        - Apply netplan
        - Restart systemd

  handlers:
    - name: Apply netplan
      shell: "netplan apply"
   
    - name: Restart systemd
      service:
        name: systemd-resolved
        state: restarted
        enabled: yes
