- name: Untar prometheus
  unarchive:
    src: /opt/prometheus-{{ prom_version }}.linux-amd64.tar.gz
    dest: /opt/prometheus/
    remote_src: yes
    mode: '0755'
    owner: "{{ prom_user }}"
    extra_opts:
      - --strip-components=1

- name: Restart systemd
  shell: "systemctl daemon-reload"

- name: Restart prometheus
  service:
   name: prometheus
   state: restarted
