- name: Restart MySQL
  service:
    name: mysql
    state: restarted

- name: Restart systemd
  shell: "systemctl daemon-reload"

- name: Restart exporter
  service:
    name: mysqld_exporter
    state: restarted
