---
- name: Configuring frontend
  hosts: frontend_servers
  remote_user: dariagory
  become: yes
  vars:
    password: !vault |
	      $ANSIBLE_VAULT;1.1:AES256
		  31656530373835303063353461393063303833613062326666356665666463383534316535333362
          3037383939353631373163383962643530393736336361660a393563343834356331303463653463
          32376531343533656464623731316666626639386364633335393833613830613532633430323761
          3666393764306430660a353333663366326632636139356137313062613631626133636533303462
          3131
  tasks:
  - name: Remove sudo password request
    copy:
      dest: /etc/sudoers.d/dariagory
      content: "dariagory ALL = NOPASSWD: ALL"
  
  - name: Install Apache
    apt: name=apache2 update_cache=yes state=latest
    
  - name: Install PHP and module for MySQL
    apt:
      name:
        - php
        - php-mysql
      update_cache: yes
      state: latest
      
  - name: Install PHP module for Apache
    apt: name=libapache2-mod-php update_cache=yes state=latest
    
  - name: Set custom port
    copy:
      src: ports.conf
      dest: /etc/apache2/ports.conf
    notify:
      - Restart Apache
      
  - name: Add config for port 8080
    copy: 
      src: 8080-default.conf
      dest: /etc/apache2/ports.conf
    notify:
      - Restart Apache
      
  - name: Download WordPress
    get_url:
      url: https://wordpress.org/latest.tar.gz
      dest: /tmp/wordpress.tar.gz
      validate_certs: no

  - name: Extract WordPress
    unarchive:
      src: /tmp/wordpress.tar.gz
      dest: /var/www/
      copy: no
      creates: /var/www/wordpress
      
  - name: Update default Apache site
    lineinfile:
      dest: /etc/apache2/sites-enabled/000-default.conf
      regexp: "(.) +DocumentRoot /var/www/html"
      line: "DocumentRoot /var/www/wordpress"
    notify:
      - Restart Apache
      
  - name: Create a file to copy config
    file:
      path: /home/dariagory/lab4/wp-config-temp.php.j2
      state: touch
      owner: dariagory
      group: dariagory
      mode: 0755
      
  - name: Copy sample WP config into template
    template:
      src: /var/www/wordpress/wp-config-sample.php
      dest: /home/dariagory/lab4/wp-config-temp.php.j2
      
  - name: Change DB name in template
    lineinfile:
      dest: /home/dariagory/lab4/wp-config-temp.php.j2
      regexp: "define\\( 'DB_NAME', '(.)+' \\);"
      line: "define( 'DB_NAME', 'dahara_db' );"
      
  - name: Change username for DB in template
    lineinfile:
      dest: /home/dariagory/lab4/wp-config-temp.php.j2
      regexp: "define\\( 'DB_USER', '(.)+' \\);"
      line: "define( 'DB_USER', 'dariagory' );"
      
  - name: Change DB password in template
    lineinfile:
      dest: /home/dariagory/lab4/wp-config-temp.php.j2
      regexp: "define\\( 'DB_PASSWORD', '(.)+' \\);"
      line: "define( 'DB_PASSWORD', '{{ password }}' );"
      
  - name: Copy template to WP config file
    template: 
      src: /home/dariagory/lab4/wp-config-temp.php.j2
      dest: /var/www/wordpress/wp-config.php
      
  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted
    
- name: DB configuration
  hosts: database_servers
  remote_user: dariagory
  become: yes
  vars:
    password: !vault |
	      $ANSIBLE_VAULT;1.1:AES256
		  31656530373835303063353461393063303833613062326666356665666463383534316535333362
          3037383939353631373163383962643530393736336361660a393563343834356331303463653463
          32376531343533656464623731316666626639386364633335393833613830613532633430323761
          3666393764306430660a353333663366326632636139356137313062613631626133636533303462
          3131
  tasks:
  - name: Install packages for MySQL
    apt:
      name:
        - python-mysqldb
        - mysql-server
        - mysql-client
      update_cache: yes
      state: latest
      
  - name: Create a DB
    mysql_db:
      name: dahara_db
      state: present
      
  - name: Create a DB user
    mysql_user:
      name: dariagory
      password: "{{ password }}"
      priv: '*.*:ALL'
      state: present