- name: Enable server-status reports
  template:
    src: server-status.conf.j2
    dest: /etc/apache2/conf-available/server-status.conf
    mode: '0755'
    owner: "{{ apache_user }}"
  notify:
    - Restart apache

- name: Download go
  get_url:
    url: https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz
    dest: /opt/go{{ go_version }}.linux-amd64.tar.gz

- name: Create folder for go
  file:
    path: /opt/go
    state: directory
    mode: '0755'
    owner: "{{ apache_user }}"

- name: Untar go
  unarchive:
    src: /opt/go{{ go_version }}.linux-amd64.tar.gz
    dest: /opt/go
    remote_src: yes

- name: Create a symbolic link
  file:
    src: /opt/go/go/bin/go
    dest: /usr/local/bin/go
    state: link

- name: Install git
  apt: name=git state=present update_cache=yes

- name: Go get apache exporter
  shell: "go get -v github.com/Lusitaniae/apache_exporter"

- name: Copy binary
  copy:
    src: /root/go/bin/apache_exporter
    dest: /usr/local/bin/apache_exporter
    mode: '0755'
    remote_src: yes

- name: Create apache_exporter service
  template:
    src: apache_exporter.service.j2
    dest: /etc/systemd/system/apache_exporter.service
    mode: '0755'
    owner: "{{ apache_user }}"

- name: Create a sysconfig folder
  file:
    path: /etc/sysconfig
    state: directory
    owner: "{{ apache_user }}"
    mode: '0755'

- name: Create a sysconfig file
  template:
    src: apache_exporter.j2
    dest: /etc/sysconfig/apache_exporter
    owner: "{{ apache_user }}"
    mode: '0755'
  notify:
    - Reload systemd
    - Start apache_exporter
