---
- name: Set up backup agent
  hosts: server01
  become: yes
  tasks:
    - name: Create a new user for backups
	  user: 
	    name: "{{ user }}"
		password: "{{ password }}"
		state: present
		groups: bind
		append: yes
		shell: /bin/bash
		
	- name: Create .ssh dir
	  file:
	    path: /home/{{ user }}/.ssh
		state: directory
		owner: "{{ user }}"
        
    - name: Copy private key
      template:
        src: files/id_rsa_agent
        dest: /home/{{ user }}/.ssh/id_rsa
        
    - name: Copy public key
      template:
        src: files/id_rsa_agent.pub
        dest: /home/{{ user }}/.ssh/id_rsa.pub
        
    - name: Install duplicity
      package: name=duplicity state=present
      
    - name: Create /var/backup
      file:
        path: /var/backup
        state: directory
        owner: "{{ user }}"
        mode: '0755'